export const GET_USERS = "GET_USERS";
export const CURRENT_USER = "CURRENT_USER";
export const LOGOUT = "LOGOUT";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const SET_REQUESTED_PAGE = "SET_REQUESTED_PAGE";
export const CLEAR_REQUESTED_PAGE = "CLEAR_REQUESTED_PAGE";
